-- Migration: change_id_to_serial
-- Description: Drop and recreate the characters table to change the id column from TEXT to BIGINT GENERATED BY DEFAULT AS IDENTITY

-- 1. Drop existing characters table
DROP TABLE IF EXISTS public.characters CASCADE;

-- 2. Recreate characters table
CREATE TABLE public.characters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    privacy TEXT NOT NULL CHECK (privacy IN ('public', 'followers', 'private')) DEFAULT 'public',
    
    -- Cover Fields
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    alias TEXT,
    status TEXT NOT NULL CHECK (status IN ('alive', 'dead')),
    server_domain TEXT NOT NULL,
    discord_url TEXT,
    eyebrow TEXT NOT NULL,
    ref TEXT NOT NULL,
    photos TEXT[] NOT NULL,
    
    -- Cover Meta
    age INTEGER NOT NULL,
    taille TEXT NOT NULL,
    poids TEXT NOT NULL,
    origines TEXT NOT NULL,
    vehicule_ref TEXT NOT NULL,
    
    -- Structured chapters (JSONB)
    chapter1 JSONB NOT NULL,
    chapter2 JSONB NOT NULL,
    chapter3 JSONB NOT NULL,
    chapter4 JSONB, -- Optional
    chapter5 JSONB, -- Optional
    chapter6 JSONB NOT NULL,
    family JSONB, -- Optional
    footer TEXT NOT NULL,
    
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- 3. Enable RLS on characters
ALTER TABLE public.characters ENABLE ROW LEVEL SECURITY;

-- 4. Recreate RLS Policies
CREATE POLICY "Users can insert their own characters" 
    ON public.characters FOR INSERT 
    WITH CHECK (auth.uid() = owner_id);

CREATE POLICY "Users can update their own characters" 
    ON public.characters FOR UPDATE 
    USING (auth.uid() = owner_id);

CREATE POLICY "Users can delete their own characters" 
    ON public.characters FOR DELETE 
    USING (auth.uid() = owner_id);

CREATE POLICY "View characters based on privacy rules" 
    ON public.characters FOR SELECT 
    USING (
        privacy = 'public'
        OR owner_id = auth.uid()
        OR (
            privacy = 'followers'
            AND EXISTS (
                SELECT 1 FROM public.follows
                WHERE follower_id = auth.uid()
                AND following_id = owner_id
            )
        )
    );
